### ISSUE TITLE
Container Restarting Every 15 Seconds

### ISSUE THREAD

**Issue by webboty** [zecure/shadowdctl#1]
Hi, 

after running the `./shadowdctl up` command all containers work properly.
Connectors operate great as well.

After rebooting the server or restarting the containers ... the zecure/shadowd:2 container keeps restarting itself every 15 seconds +/-. 

```
docker ps -a

CONTAINER ID   IMAGE                          COMMAND                  CREATED       STATUS         PORTS                    NAMES
9d31dfc83ed1   zecure/shadowd:2               "/docker-entrypoint.…"   2 hours ago   Up 4 seconds   0.0.0.0:9115->9115/tcp   shadowdctl_shadowd_1
3b4dd978a882   zecure/shadowd_ui:2            "/docker-entrypoint.…"   2 hours ago   Up 2 hours     0.0.0.0:8888->80/tcp     shadowdctl_web_1
91446ce5f409   zecure/shadowd_database:12.4   "docker-entrypoint.s…"   2 hours ago   Up 2 hours     5432/tcp                 shadowdctl_db_1
```

This causes the app shadowd is supposed to protect to not work anymore with the following error:

```
shadowd\Exceptions\ProcessingException
#0 /usr/share/shadowd/php/src/Connection.php(90): shadowd\Connection->parseOutputData()
#1 /usr/share/shadowd/php/src/Connector.php(55): shadowd\Connection->send()
#2 /usr/share/shadowd/php/shadowd.php(26): shadowd\Connector->start()
#3 {main}
```

The shadowd admin panel is working though.

The only way i get everything to work again is re-downloading the containers via:
`./shadowdctl up -d --force-recreate`

Then everything works again until the machine is rebooted or the container is stopped and restarted.

System: Ubuntu 20.04
All Firewalls: Deactivated
Webserver: NGINX 1.18

What are your suggestions?

Thanks in advance

**Comment by webboty** [comment]
It return this:

`Starting command /usr/bin/shadowd -c /etc/shadowd/shadowd.ini -U shadowd -G shadowd
Configuration error: invalid configuration file`
